import {FormState} from '@app/utils/store/formsSlice';
import {EntityState} from '@reduxjs/toolkit';

export type ResponseOption = 'N/A' | 'Must Have' | 'Like To Have' | 'Maybe' | 'Off Limits';

// export interface Responses {
//   [label: string]: {
//     valueOptions: string[],
//     value: string,
//     hoverOver?: string,
//   };
// }

const DEFAULT_RESPONSE_OPTIONS: ResponseOption[] = ['N/A', 'Must Have', 'Like To Have', 'Maybe', 'Off Limits'];
const DEFAULT_RESPONSE: string = 'N/A';


export const nonEscalatorMenu: FormState = {
  formId: 'NonEscalatorRelationship',
  formName: 'Non Escalator Relationship',
  fieldGroups: {
    'Commitment': {
      fieldGroupId: 'Commitment',
      fieldGroupLabel: 'Commitment',
      nextFieldGroupId: 'PhysicalIntimacy',
      fields: {
        'marriage': {
          id: 'marriage',
          label: 'Marriage',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE},
        'sharing-pets': {
          id: 'sharing-pets',
          label: 'Sharing pet(s)',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'pregnancy-children': {
          id: 'pregnancy-children',
          label: 'Pregnancy/children together',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'coparenting': {
          id: 'coparenting',
          label: 'Coparenting children from other partners',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'having-a-key': {
          id: 'having-a-key',
          label: 'Having a key',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'cohabitation': {
          id: 'cohabitation',
          label: 'Cohabitation',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'home-ownership': {
          id: 'home-ownership',
          label: 'Home ownershipt',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'priority-over-other-partners': {
          id: 'priority-over-other-partners',
          label: 'Prioritization over other partners',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'relationship-labels': {
          id: 'relationship-labels',
          label: 'Relationship labels',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'planning-for-the-future': {
          id: 'planning-for-the-future',
          label: 'Planning for the future',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'expectation-of-long-term-involvement': {
          id: 'expectation-of-long-term-involvement',
          label: 'Expectation of long term involvement',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'commitment-to-working-through-challenges': {
          id: 'commitment-to-working-through-challenges',
          label: 'Commitment to working through challenges',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'power-of-attorney': {
          id: 'power-of-attorney',
          label: 'Power of attorney/wills',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'support-through-health-challenges': {
          id: 'support-through-health-challenges',
          label: 'Support through health challenges',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
      },
    },
    'PhysicalIntimacy': {
      fieldGroupId: 'PhysicalIntimacy',
      fieldGroupLabel: 'Physical Intimacy',
      nextFieldGroupId: 'EmotionalIntimacy',
      previousFieldGroupId: 'Commitment',
      fields: {
        'physical-affection': {
          id: 'physical-affection',
          label: 'Physical affection',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'pda': {
          id: 'pda',
          label: 'PDA',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'compatible-sex-drive': {
          id: 'compatible-sex-drive',
          label: 'Compatible sex drive',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'sexual-chemistry': {
          id: 'sexual-chemistry',
          label: 'Sexual chemistry',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'orgasms': {
          id: 'orgasms',
          label: 'Orgasms',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'kissing': {
          id: 'kissing',
          label: 'Kissing',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'oral-sex': {
          id: 'oral-sex',
          label: 'Oral sex',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'manual-sex': {
          id: 'manual-sex',
          label: 'Manual sex (fingering)',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'mutual-masturbation': {
          id: 'mutual-masturbation',
          label: 'Mutual masturbation',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'penetration': {
          id: 'penetration',
          label: 'Penetration/PIV',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'using-sex-toys': {
          id: 'using-sex-toys',
          label: 'Using sex toys',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'condom-use': {
          id: 'condom-use',
          label: 'Condom/barrier use',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'regular-sti-testing': {
          id: 'regular-sti-testing',
          label: 'Regular STI testing',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'kinky-stuff': {
          id: 'kinky-stuff',
          label: 'Kinky stuff',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'threesomes-group-sex': {
          id: 'threesomes-group-sex',
          label: 'Threesomes or group sex',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
      },
    },
    'EmotionalIntimacy': {
      fieldGroupId: 'EmotionalIntimacy',
      fieldGroupLabel: 'Emotional Intimacy',
      nextFieldGroupId: 'Communication',
      previousFieldGroupId: 'PhysicalIntimacy',
      fields: {
        'expressing-happiness': {
          id: 'expressing-happiness',
          label: 'Expressing happiness and joy',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'offering-support-in-hard-times': {
          id: 'offering-support-in-hard-times',
          label: 'Offering support in hard times',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'sharing-vulnerable-feelings': {
          id: 'sharing-vulnerable-feelings',
          label: 'Sharing vulnerable feelings',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'saying-i-love-you': {
          id: 'saying-i-love-you',
          label: 'Saying "I love you"',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'sharing-stories-about-past': {
          id: 'sharing-stories-about-past',
          label: 'Sharing stories about past',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'sharing-hopes-for-future': {
          id: 'sharing-hopes-for-future',
          label: 'Sharing hopes for future',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'knowing-personal-preferences': {
          id: 'knowing-personal-preferences',
          label: 'Knowing personal likes/dislikes (eg favorite food)',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'using-pet-names': {
          id: 'using-pet-names',
          label: 'Using pet names',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'sharing-mental-health-challenges': {
          id: 'sharing-mental-health-challenges',
          label: 'Sharing about mental health challenges',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'Supporting mental health work': {
          id: 'supporting-mental-health-work',
          label: 'Supporting mental health work',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
      },
    },
    'Communication': {
      fieldGroupId: 'Communication',
      fieldGroupLabel: 'Communication',
      nextFieldGroupId: 'FinancialManagement',
      previousFieldGroupId: 'EmotionalIntimacy',
      fields: {
        'daily-check-ins': {
          id: 'daily-check-ins',
          label: 'Daily or frequent check ins',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'texting': {
          id: 'texting',
          label: 'Texting',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'phone-video-calls': {
          id: 'phone-video-calls',
          label: 'Phone / video calls',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'discussing-work-and-hobbies': {
          id: 'discussing-work-and-hobbies',
          label: 'Discussing work and hobbies',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'discussing-family': {
          id: 'discussing-family',
          label: 'Discussing family',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'discussing-friends': {
          id: 'discussing-friends',
          label: 'Discussing friends',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'discussing-partners': {
          id: 'discussing-partners',
          label: 'Discussing partners',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'discussing-politics': {
          id: 'discussing-politics',
          label: 'Discussing politics and current events',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'ability-to-express-disagreement': {
          id: 'ability-to-express-disagreement',
          label: 'Ability to express disagreement and hurt feelings',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'ability-to-address-conflict': {
          id: 'ability-to-address-conflict',
          label: 'Ability to address and resolve conflict',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'radical-honesty': {
          id: 'radical-honesty',
          label: 'Radical honesty',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
      },
    },
    'FinancialManagement': {
      fieldGroupId: 'FinancialManagement',
      fieldGroupLabel: 'Financial Management',
      nextFieldGroupId: 'SocialIntegration',
      previousFieldGroupId: 'Communication',
      fields: {
        'shared-bank-account': {
          id: 'shared-bank-account',
          label: 'Shared bank account(s)',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'mutual-contributions-to-vacation': {
          id: 'mutual-contributions-to-vacation',
          label: 'Mutual contributions to vacation/activity fund',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'financial-support': {
          id: 'financial-support',
          label: 'Financial support',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'large-gifts': {
          id: 'large-gifts',
          label: 'Large gifts',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'complete-financial-integration': {
          id: 'complete-financial-integration',
          label: 'Complete financial integration',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
      },
    },
    'SocialIntegration': {
      fieldGroupId: 'SocialIntegration',
      fieldGroupLabel: 'Social Integration',
      previousFieldGroupId: 'FinancialManagement',
      nextFieldGroupId: 'FinishedForm',
      fields: {
        'meeting-metamors': {
          id: 'meeting-metamors',
          label: 'Meeting metamors (partners other partners)',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'meeting-children': {
          id: 'meeting-children',
          label: 'Meeting children',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'meeting-parents': {
          id: 'meeting-parents',
          label: 'Meeting parents/siblings/extended family',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
        'meeting-friends': {
          id: 'meeting-friends',
          label: 'Meeting friends',
          type: 'selectField',
          valueOptions: DEFAULT_RESPONSE_OPTIONS,
          value: DEFAULT_RESPONSE,
        },
      },
    },
  },
};

export const relationshipForms: EntityState<FormState> = {
  ids: ['NonEscalatorRelationship'],
  entities: {
    'NonEscalatorRelationship': nonEscalatorMenu,
  },
};
