import React from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import TailwindForm from '../components/FormPageLayout';
import { nonEscalatorMenu } from '../utils/store/questions';


const Home: NextPage = () => {

  React.useEffect(() => {

    const fn = async () => {
      const Peer = (await import('simple-peer')).default;
      console.log(Peer.WEBRTC_SUPPORT)
      // set it to state here
      const peer1 = new Peer({ initiator: true })
      const peer2 = new Peer();
    
      peer1.on('signal', data => {
        console.log(data);
        peer2.signal(data);
      });
    
      peer2.on('signal', data => {
        peer1.signal(data);
      });
    
      peer1.on('connect', () => {
        peer1.send('hey peer2, how is it going?');
      });
    
      peer2.on('data', data => {
        console.log('got a message from peer1: ' + data);
      })
    }
    fn()
  }, []); 


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        <h1>
          Non-escalator Relationship Menu
        </h1>
        {/* {Object.keys(nonEscalatorMenu).map((category) => (
          <TailwindForm
            key={category}
            category={category}
            responses={nonEscalatorMenu.categories[category]}
          />
        ))} */}

    </div>
  )
}

export default Home
